In [15]:
import numpy as np

In [16]:
a = np.arange(12).reshape(3,4)
b = np.arange(10,22).reshape(3,4)
c = np.dot(a, b)

print(c)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [5]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)
c = np.dot(a, b)

In [9]:
mylist = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

print(mylist)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [3]:
# 1. Create a 1D array of numbers from 0 to 9
array1d = ([0,1,2,3,4,5,6,7,8,9])
print(array1d)
#/
array1d = np.arange(10)
print(array1d)
print("\n")

# 2. Create a 3×3 NumPy array of all Boolean value Trues
array3d = ([[1,2,3],[4,5,6],[7,8,9]])
print(array3d)
array3d = np.ones(9)
array3d2 = array3d.reshape(3,3)
print(array3d2)
boolarra = np.ones((3,3), dtype = bool)
print(boolarra)
print("\n")

# 3. Extract all odd numbers from array of 1-10
arrayX= ([1,2,3,4,5,6,7,8,9,10])
ArrayXSlice = arrayX[::2]
print(ArrayXSlice)
print("\n")

#4. Replace all odd numbers in an array of 1-10 with the value -1
array1d[array1d%2 == 1] = -1
print(array1d)
print("\n")

# 5. Convert a 1D array to a 2D array with 2 rows
arayt = np.array([1,2,3,4,5,6,7,8,9,10])
Transarray = arayt.reshape(2, 5)
print(Transarray)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[1, 3, 5, 7, 9]


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
# 1. Create the following pattern without hardcoding. Use only NumPy functions. 111222333123123123
ar = np.ones(3)
ar1 = np.arange(1,4)
ar2 = np.concatenate((ar, ar*2, ar*3, ar1, ar1, ar1))
print(ar2)

print("")
#2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

a1 = np.arange(1, 6)
a2 = np.array([4,5,6,7,8,9])
aa = np.concatenate((a1, a2))
print(aa)
print(np.unique(aa))

print("")
#3. Get all items between 3 and 7 from a and b and sum themtogether
print(aa[3:8])
print(np.sum(aa[3:8]))

[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]

[1 2 3 4 5 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

[4 5 4 5 6]
24


In [18]:
"""Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
• 3
• 45
• 83
• 21
Have a go at ‘w’ ‘r’ ‘a’ """
num = input("choose number ")
num1 = input("choose number 2")
num2 = input("choose number 3")
num3 = input("choose number 4")



In [4]:
a1 = open("numbers.txt", "w")
a1.write(num+"\n"+num1+"\n"+num2)
a1.close()

In [5]:
a3 = open("numbers.txt", "a")
a3.write("\n"+num3)
a3.close

<function TextIOWrapper.close()>

In [31]:
a2 = open("numbers.txt", "r")
print(a2.read())

3
45
83
21


In [20]:
""" Write a program to ask a student for their percentage mark and convert this to a grade.... Call the grade mark_grade"""

def mark_grade(): 
    percentage = float(0)
   
    try:
        percentage = float(input("Please enter your score out of 100"))
    except:
        print("invalid input")
        percentage = float(input("Please enter your score out of 100"))
    
    while percentage < 0 and percentage > 101:
        print("invalid input")
    else:
        if percentage > 69:
            print("You have achieved a First Class degree")
        elif percentage <= 69 and percentage > 59:
            print("You have achieved a 2:1 degree")
        elif percentage <= 59 and percentage > 49:
            print("You have achieved a 2:2 degree")
        elif percentage < 40:
            print("You have Failed your course")
        else:
            print("You have achieved a Third Class degree")    
        
mark_grade()

invalid input
You have achieved a First Class degree


In [21]:
def mark():
    percentage = float(0)
   
    try:
        percentage = float(input("Please enter your score out of 100"))
    except:
        print("invalid input")
        percentage = float(input("Please enter your score out of 100"))
    
    while percentage < 0 and percentage > 101:
        print("invalid input")
    else:
        return percentage

In [28]:
""" Extension to Task 2 • Ask the user for their target grade and print this with their mark • If their target grade > exam grade display a suitable message • If their target grade = exam grade display a suitable message • If their target grade < exam grade display a suitable message """
Code = ["A","a","B","b","C","c","D","d"]

percentage = float(mark())
target = str(input("What grade did you target for yourself? \n Type \"A\" if your target was a First class degree \t Type \"A\" if your target was a First class degree \t Type \"B\" if your target was a 2:1 degree \t Type \"C\" if your target was a 2:2 degree"))

while target not in Code:
    print("Invalid input")
    target = str(input("What grade did you target for yourself? \n Type \"A\" if your target was a First class degree \t Type \"A\" if your target was a First class degree \t Type \"B\" if your target was a 2:1 degree \t Type \"C\" if your target was a 2:2 degree \t Type \"D\" if your target was a Third class degree"))
else:
    if target == "A" or target == "a":
        if percentage >= 70.0:
            print("Congratulations You have achieved your target grade by", percentage - 70.0,"marks")
        else:
            print("You were", 70.0 - percentage, "percentage marks away from achieving your target grade")
    elif target == "B" or target == "b":
        if percentage >= 60.0:
            print("Congratulations You have achieved your target grade by", percentage - 60.0,"marks")
        else:
            print("You were", 60.0 - percentage, "percentage marks away from achieving your target grade")
    elif target == "C" or target == "c":
        if percentage >= 50.0:
            print("Congratulations You have achieved your target grade by", percentage - 50.0,"marks")
        else:
            print("You were", 50.0 - percentage, "percentage marks away from achieving your target grade")
    else:
        if percentage >= 40.0:
            print("Congratulations You have achieved your target grade by", percentage - 40.0,"marks")
        else:
            print("You were", 40.0 - percentage, "percentage marks away from achieving your target grade")

invalid input
You were 12.5 percentage marks away from achieving your target grade
